import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";

/**
 * GET /api/trends/signals?themeSlug=game-day
 * Returns trend signal + series + seasonal profile for a specific theme
 *
 * NOTE: Returns mock/placeholder data if no signal exists yet
 * Real signals are generated by background jobs calling SerpAPI
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const themeSlug = searchParams.get("themeSlug");

    if (!themeSlug) {
      return NextResponse.json(
        { success: false, error: "themeSlug parameter required" },
        { status: 400 },
      );
    }

    // Get theme details using RPC function
    const { data: themes, error: themeError } =
      await supabaseAdmin.rpc("get_active_themes");

    if (themeError) {
      console.error("Error fetching themes:", themeError);
      return NextResponse.json(
        { success: false, error: "Failed to fetch theme" },
        { status: 500 },
      );
    }

    const theme = themes?.find((t: { slug: string }) => t.slug === themeSlug);

    if (!theme) {
      return NextResponse.json(
        { success: false, error: "Theme not found" },
        { status: 404 },
      );
    }

    // TODO: Create RPC functions for trend_signals, trend_series, seasonal_profiles
    // For now, return placeholder data indicating no signal exists yet

    return NextResponse.json({
      success: true,
      theme,
      signal: null, // Will be populated by background job
      series: [], // Will be populated by background job
      seasonalProfile: null, // Will be populated by background job
      message: "No signal data yet - background jobs will populate this",
    });
  } catch (error) {
    console.error("Unexpected error in GET /api/trends/signals:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 },
    );
  }
}
