import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";

/**
 * GET /api/trends/signals?themeSlug=game-day
 * Returns trend signal + series + seasonal profile for a specific theme
 *
 * NOTE: Returns mock/placeholder data if no signal exists yet
 * Real signals are generated by background jobs calling SerpAPI
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const themeSlug = searchParams.get("themeSlug");

    if (!themeSlug) {
      return NextResponse.json(
        { success: false, error: "themeSlug parameter required" },
        { status: 400 },
      );
    }

    // Get theme details using RPC function
    const { data: themes, error: themeError } =
      await supabaseAdmin.rpc("get_active_themes");

    if (themeError) {
      console.error("Error fetching themes:", themeError);
      return NextResponse.json(
        { success: false, error: "Failed to fetch theme" },
        { status: 500 },
      );
    }

    const theme = themes?.find((t: { slug: string }) => t.slug === themeSlug);

    if (!theme) {
      return NextResponse.json(
        { success: false, error: "Theme not found" },
        { status: 404 },
      );
    }

    // Get first active shop for testing purposes
    // TODO: In production, get shop_id from authenticated session
    const { data: shopData, error: shopError } = await supabaseAdmin
      .from("shops")
      .select("id")
      .eq("is_active", true)
      .limit(1)
      .single();

    if (shopError || !shopData) {
      console.error("Error fetching shop:", shopError);
      return NextResponse.json(
        { success: false, error: "No active shop found" },
        { status: 404 },
      );
    }

    const shopId = shopData.id;

    // Get signal data using RPC function
    const { data: signalData, error: signalError } = await supabaseAdmin.rpc(
      "get_trend_signal",
      {
        p_shop_id: shopId,
        p_theme_id: theme.id,
      },
    );

    if (signalError) {
      console.error("Error fetching signal:", signalError);
    }

    const signal = signalData?.[0] || null;

    // Get series data using RPC function
    const { data: seriesData, error: seriesError } = await supabaseAdmin.rpc(
      "get_trend_series",
      {
        p_shop_id: shopId,
        p_theme_id: theme.id,
        p_granularity: "weekly",
      },
    );

    if (seriesError) {
      console.error("Error fetching series:", seriesError);
    }

    const series = seriesData?.[0]?.points || [];

    return NextResponse.json({
      success: true,
      theme,
      signal,
      series,
      seasonalProfile: null, // TODO: implement seasonal profiles
    });
  } catch (error) {
    console.error("Unexpected error in GET /api/trends/signals:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 },
    );
  }
}
