# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration

api_version = "2025-07"

[[extensions]]
name = "enhance-product-action"
handle = "enhance-product-action"
uid = "be246396-9266-f9c1-940d-d0a645540fb08f32b355"
type = "ui_extension"

[[extensions.extension_points]]
target = "admin.product-details.action.render"
module = "./src/ActionExtension.jsx"