-- ============================================================================
-- Ad Intelligence Engine (AIE) - Seed Best Practices
-- ============================================================================
-- Description: Seeds initial best practices data for AIE RAG system
-- Version: 1.0.0
-- Date: 2025-11-06
-- Depends on: 20251106_aie_core_schema.sql
-- ============================================================================

-- Note: Embeddings will be generated by the application layer
-- This seed includes foundational best practices across platforms

-- ============================================================================
-- META/INSTAGRAM BEST PRACTICES
-- ============================================================================

INSERT INTO aie_best_practices (title, platform, category, goal, format, description, example_text, framework_type, source_type, verification_status, tags) VALUES
-- Hook Frameworks
('Start with a Question Hook', 'meta', 'all', 'engagement', 'all',
 'Opening with a compelling question immediately engages the audience and encourages them to keep reading. Questions should be relevant to the pain point or desire.',
 'Are you tired of spending hours on [problem]? What if you could [solution] in just 5 minutes?',
 'hook', 'public', 'verified',
 ARRAY['hook', 'question', 'engagement']),

('Use the Pain-Point-Agitate-Solve Framework', 'meta', 'all', 'conversion', 'all',
 'Identify a specific pain point, agitate it to make the reader feel the urgency, then present your product as the solution.',
 'Struggling with [pain]? It gets worse when [agitation]. Our [product] solves this by [benefit].',
 'structure', 'public', 'verified',
 ARRAY['pas', 'framework', 'conversion']),

('Lead with Social Proof', 'meta', 'all', 'all', 'all',
 'Start with a credible statistic, testimonial, or customer count to establish trust immediately.',
 'Join 50,000+ customers who have already [achieved result]. "This changed my life!" - Sarah M.',
 'hook', 'public', 'verified',
 ARRAY['social_proof', 'trust', 'testimonial']),

-- Platform-Specific Best Practices
('Keep Primary Text Under 125 Characters', 'meta', 'all', 'all', 'static',
 'Meta shows only the first 125 characters in feed. Front-load the most important message to grab attention before "See More".',
 NULL,
 'formatting', 'public', 'verified',
 ARRAY['meta', 'character_limit', 'formatting']),

('Use Emojis Strategically (Max 2-3)', 'meta', 'all', 'all', 'all',
 'Emojis can increase engagement by 48% but overuse looks spammy. Use 2-3 relevant emojis to add visual interest.',
 '✨ Transform your [outcome] 🚀 in just [timeframe]!',
 'formatting', 'public', 'verified',
 ARRAY['emojis', 'visual', 'engagement']),

-- Headline Best Practices
('Headlines Should Promise a Clear Benefit', 'meta', 'all', 'conversion', 'all',
 'The headline should immediately communicate what the customer gets. Use numbers and specificity when possible.',
 'Get 10x Better Results in Half the Time | Save $500 on Your First Order',
 'headline', 'public', 'verified',
 ARRAY['headline', 'benefit', 'specificity']),

-- CTA Best Practices
('Match CTA to Campaign Goal', 'meta', 'all', 'all', 'all',
 'Awareness campaigns: Learn More. Conversion campaigns: Shop Now/Sign Up. Match button text to user intent.',
 'Awareness: "Learn More" | Conversion: "Shop Now" | Lead Gen: "Get Your Free Guide"',
 'cta', 'public', 'verified',
 ARRAY['cta', 'alignment', 'conversion']),

-- Category-Specific
('Apparel: Focus on Style + Comfort', 'meta', 'apparel', 'conversion', 'all',
 'For fashion/apparel, emphasize both aesthetic appeal and practical comfort. Include fabric details and fit.',
 'Effortlessly chic meets all-day comfort. Premium cotton blend that moves with you. ✨',
 'content', 'public', 'verified',
 ARRAY['apparel', 'fashion', 'product_description']),

('Beauty: Lead with Transformation', 'meta', 'beauty', 'conversion', 'all',
 'Beauty products sell transformation, not ingredients. Show the before/after or the feeling they''ll get.',
 'Radiant skin in just 7 days 💫 Dermatologist-tested formula that actually works.',
 'content', 'public', 'verified',
 ARRAY['beauty', 'transformation', 'results']),

('Electronics: Specs + Lifestyle Benefits', 'meta', 'electronics', 'conversion', 'all',
 'Balance technical specs with lifestyle benefits. Show how the tech improves daily life.',
 '🔋 72-hour battery life = Weekend adventures without the charger anxiety',
 'content', 'public', 'verified',
 ARRAY['electronics', 'specs', 'lifestyle']),

-- Urgency & Scarcity
('Use Time-Limited Urgency Authentically', 'meta', 'all', 'conversion', 'all',
 'Urgency works but must be genuine. Flash sales, limited stock, or seasonal offers create real FOMO.',
 '⏰ Flash Sale Ends Tonight! Only 47 left in stock',
 'urgency', 'public', 'verified',
 ARRAY['urgency', 'scarcity', 'fomo']),

-- Seasonal Best Practices
('Holiday Ads: Gifting Angle + Urgency', 'meta', 'all', 'conversion', 'all',
 'During holidays, position product as the perfect gift and add delivery deadline urgency.',
 '🎁 The Perfect Gift for [recipient]. Order by Dec 18 for Christmas delivery!',
 'seasonal', 'public', 'verified',
 ARRAY['holiday', 'gifting', 'seasonal']),

-- ============================================================================
-- GOOGLE ADS BEST PRACTICES
-- ============================================================================

('Google: Use All 15 Headline Slots', 'google', 'all', 'all', 'all',
 'Responsive Search Ads perform best with 15 unique headlines testing different angles (benefits, features, social proof, questions).',
 'Headline 1: Save Time | Headline 2: Join 10,000+ Users | Headline 3: Try Free for 30 Days',
 'headline', 'public', 'verified',
 ARRAY['google', 'rsa', 'headlines']),

('Google: Include Keywords in Headlines', 'google', 'all', 'conversion', 'all',
 'Boost Quality Score by including search keywords in at least 2 headlines. Shows relevance to searchers.',
 'If keyword is "project management software": Headline 1: Best Project Management Software',
 'headline', 'public', 'verified',
 ARRAY['google', 'keywords', 'quality_score']),

('Google: Descriptions Should Add New Info', 'google', 'all', 'all', 'all',
 'Don''t repeat headline info in descriptions. Use descriptions to add features, benefits, or proof.',
 'Headline: "Save 10 Hours/Week" | Description: "Automated workflows + real-time collaboration. Trusted by Fortune 500."',
 'content', 'public', 'verified',
 ARRAY['google', 'description', 'information']),

-- ============================================================================
-- UNIVERSAL BEST PRACTICES (All Platforms)
-- ============================================================================

('Always Include a Clear Value Proposition', 'all', 'all', 'all', 'all',
 'Within the first sentence, make it crystal clear what you offer and why it matters to the customer.',
 'Transform your [problem] into [solution] without [pain point]',
 'content', 'public', 'verified',
 ARRAY['value_prop', 'clarity', 'universal']),

('Use Power Words for Emotional Impact', 'all', 'all', 'all', 'all',
 'Words like "instant", "proven", "exclusive", "guaranteed" trigger emotional responses and increase engagement.',
 'Instant results. Proven system. Exclusive access. Guaranteed satisfaction.',
 'copywriting', 'public', 'verified',
 ARRAY['power_words', 'emotion', 'copywriting']),

('Speak Directly to Your Target Audience', 'all', 'all', 'all', 'all',
 'Use "you" language and reference specific audience pain points. Generic ads convert poorly.',
 'For Busy Moms: Finally, a meal solution that your kids will actually eat 🍽️',
 'targeting', 'public', 'verified',
 ARRAY['audience', 'targeting', 'personalization']),

('Test Benefit vs Feature Headlines', 'all', 'all', 'conversion', 'all',
 'Generally, benefit-driven headlines ("Save 10 Hours/Week") outperform feature-driven ("AI-Powered Automation"), but test both.',
 'Benefit: "Sleep Better Tonight" vs Feature: "Advanced Sleep Tracking Technology"',
 'testing', 'public', 'verified',
 ARRAY['ab_testing', 'benefits', 'features']),

('Build Trust with Specificity', 'all', 'all', 'conversion', 'all',
 'Vague claims ("amazing results") are ignored. Specific numbers and details ("4.8/5 stars, 127 reviews") build trust.',
 'Vague: "Loved by many" → Specific: "4.9/5 stars from 2,847 verified buyers"',
 'trust', 'public', 'verified',
 ARRAY['specificity', 'trust', 'social_proof']),

-- ============================================================================
-- VIDEO AD BEST PRACTICES
-- ============================================================================

('Video: Hook in First 3 Seconds', 'all', 'all', 'all', 'video',
 'Most users scroll past within 3 seconds. Open with visual movement, text overlay, or pattern interrupt.',
 'Start with: Product in action | Shocking stat | Relatable problem visualization',
 'video', 'public', 'verified',
 ARRAY['video', 'hook', 'attention']),

('Video: Add Captions (85% Watch Muted)', 'all', 'all', 'all', 'video',
 '85% of social video is watched without sound. Always include captions for accessibility and engagement.',
 NULL,
 'video', 'public', 'verified',
 ARRAY['video', 'captions', 'accessibility']),

-- ============================================================================
-- UGC (User-Generated Content) BEST PRACTICES
-- ============================================================================

('UGC: Authentic Over Polished', 'all', 'all', 'all', 'video',
 'User-generated content (UGC) style ads perform 4x better than studio-quality. Keep it real and relatable.',
 'Shoot on iPhone, natural lighting, casual testimonial format. "I didn''t believe it until I tried it..."',
 'ugc', 'public', 'verified',
 ARRAY['ugc', 'authentic', 'testimonial']),

('UGC: Show Before/After Journey', 'all', 'all', 'conversion', 'all',
 'UGC ads work best when showing transformation. Have customers share their before/after experience.',
 'Day 1 vs Day 30 comparison | "I was skeptical but..." testimonial format',
 'ugc', 'public', 'verified',
 ARRAY['ugc', 'transformation', 'before_after']);

-- ============================================================================
-- UPDATE METADATA
-- ============================================================================

-- Add creation timestamp to metadata
UPDATE aie_best_practices
SET metadata = jsonb_build_object(
  'seed_version', '1.0.0',
  'last_reviewed', CURRENT_DATE,
  'source', 'initial_seed'
)
WHERE metadata = '{}';

-- ============================================================================
-- VERIFY SEED DATA
-- ============================================================================

DO $$
DECLARE
  best_practice_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO best_practice_count FROM aie_best_practices;

  RAISE NOTICE 'AIE Best Practices Seeded: % records', best_practice_count;

  IF best_practice_count < 20 THEN
    RAISE EXCEPTION 'Seed failed: Expected at least 20 best practices, got %', best_practice_count;
  END IF;
END $$;
